Parameters:
  ApplicationPort:
    Type: Number
    Default: 3000
  
  SlowStart:
    Type: Number
    Default: 300

Resources:
  awslogs:
    Type: AWS::Logs::LogGroup

  awsvpc:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: "256"
      ExecutionRoleArn: arn:aws:iam::460449571267:role/ecsTaskExecutionRole
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
      - EC2
      - FARGATE
      ContainerDefinitions:
      - Environment:
        - Name: LOG_TYPE
          Value: json
        Essential: true 
        HealthCheck:
          Command: 
          - CMD-SHELL
          - !Sub 'curl -f http://localhost:${ApplicationPort}/slow/${SlowStart} || exit 1'
          Interval: 10
          Retries: 4
          StartPeriod: !Ref SlowStart
          Timeout: 5
        Image: rimaulana/simple-express
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref awslogs
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: "log"
        MemoryReservation: 256
        Name: node 
        PortMappings:
        - ContainerPort: !Ref ApplicationPort
          Protocol: tcp
